"""Final-answer composer.

The composer is intentionally small: a deterministic template
that joins the chain's outputs into a human-readable string
plus a citations list. The LLM-driven planner is responsible
for *what* the plan does; the composer is responsible for
*how* the result is presented.

Why a template, not an LLM call
-------------------------------

* The final answer is generated by the orchestrator's chain
  (MCP tools + RAG). Re-running an LLM at this stage would
  double the cost and reintroduce the prompt-injection surface
  over the retrieved chunks.
* The brief's hard constraint #4 requires citations and a
  trace; the composer surfaces both explicitly.
* The compose step is deterministic and easy to test.
"""
from __future__ import annotations

from typing import Any

from core.domain import Citation


def compose_answer(
    *,
    intent: str,
    prior_outputs: dict[str, Any],
    citations: list[Citation],
    rag_confidence: str,
    dropped_count: int,
    trace_size: int,
) -> str:
    """Render the final answer from the chain's outputs.

    The format is a structured summary that the GUI can render
    verbatim. Sections:

    * ``Intent`` — the planner's intent string.
    * ``Findings`` — the last tool / RAG output's excerpt.
    * ``Citations`` — one bullet per citation with score.
    * ``Confidence`` — the RAG confidence band.
    * ``Trace`` — the number of MCP + RAG steps that ran.

    Parameters
    ----------
    intent:
        The planner's intent string.
    prior_outputs:
        The chain runner's per-step output dict. The "final"
        step's output is used as the findings excerpt.
    citations:
        The RAG citations the chain produced.
    rag_confidence:
        The RAG confidence band (``"high"`` / ``"medium"`` /
        ``"low"`` / ``"none"``).
    dropped_count:
        The number of chunks dropped by the injection blocklist.
    trace_size:
        The number of MCP + RAG steps.
    """
    bullets: list[str] = []
    if intent:
        bullets.append(f"Intent: {intent}")

    # The last step's output is treated as the "findings body".
    # If the last step is a dict (typical tool output), format
    # it as a short summary. If it's a string (compose step),
    # include it directly.
    if prior_outputs:
        last_key = max(prior_outputs.keys())
        last_value = prior_outputs[last_key]
        findings = _summary_excerpt(last_value)
        if findings:
            bullets.append(f"Findings:\n{findings}")

    if citations:
        cite_lines = []
        for c in citations:
            score = f"{c.score:.2f}" if c.score is not None else "n/a"
            section = f" — {c.section}" if c.section else ""
            cite_lines.append(f"  - {c.doc_id}{section} (score={score})")
        bullets.append("Citations:\n" + "\n".join(cite_lines))

    if dropped_count > 0:
        bullets.append(
            f"Note: {dropped_count} document chunk(s) were dropped "
            "by the prompt-injection blocklist before retrieval."
        )

    bullets.append(
        f"Confidence: {rag_confidence} | Trace steps: {trace_size}"
    )

    return "\n\n".join(bullets)


def _summary_excerpt(value: Any) -> str:
    """Return a short, human-readable summary of a tool / RAG output."""
    if value is None:
        return ""
    if isinstance(value, str):
        return value[:500]
    if isinstance(value, dict):
        # Common shapes: {"items": [...]}, {"results": [...]}, {"text": "..."}
        if "text" in value and isinstance(value["text"], str):
            return value["text"][:500]
        if "items" in value and isinstance(value["items"], list):
            return f"Returned {len(value['items'])} item(s)."
        if "results" in value and isinstance(value["results"], list):
            return f"Returned {len(value['results'])} result(s)."
        if "total" in value:
            return f"Total: {value['total']} match(es)."
        return str(value)[:500]
    if isinstance(value, list):
        return f"Returned {len(value)} item(s)."
    return str(value)[:500]


__all__ = ["compose_answer"]
